name: Run cargo clippy, cargo fmt, build and Unit+Integration tests

on:
  push:
    branches:
      master
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Run static analysis
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    strategy:
      matrix:
        target: ["nanos", "nanox", "nanosplus"]
        package: [include_gif, testmacro, ledger_secure_sdk_sys, ledger_device_sdk]
    steps:
      - name: Print Environment variables
        run: 
          echo "The value of RUST_NIGHTLY is $RUST_NIGHTLY"
      - name: Clone
        uses: actions/checkout@v4
      - name: Cargo clippy
        run: |
          cargo +$RUST_NIGHTLY clippy -p ${{ matrix.package }} --target ${{ matrix.target }}
  
  clippy-cargo-ledger:
    name: Run static analysis for cargo-ledger
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Cargo clippy for cargo-ledger
        run: |
          cargo +$RUST_STABLE clippy -p cargo-ledger --no-deps

  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Run cargo fmt
        run: |
          cargo +$RUST_NIGHTLY fmt --all --check

  build:
    name: Build SDK
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    strategy:
      matrix:
        target: ["nanos", "nanox", "nanosplus"]
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Cargo build
        run: |
          cargo +$RUST_NIGHTLY build -p ledger_device_sdk --target ${{ matrix.target }}

  build-cargo-ledger:
    name: Build SDK
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Cargo build
        run: |
          cargo +$RUST_STABLE build -p cargo-ledger

  test:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    strategy:
      matrix:
        target: ["nanos", "nanox", "nanosplus"]
    steps:
      - name: Force speculos update
        run: |
          pip3 install --no-cache-dir speculos --upgrade
      - name: Clone
        uses: actions/checkout@v4
      - name: Unit tests
        run: |
          cargo +$RUST_NIGHTLY test -p ledger_device_sdk --target ${{ matrix.target }} --features speculos --tests
