name: Rust

on:
  push:
    branches:
      master
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Run static analysis
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    strategy:
      matrix:
        target: ["nanos", "nanox", "nanosplus"]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p ledger_device_sdk --target ledger_device_sdk/${{ matrix.target }}.json
  
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -p ledger_device_sdk --all -- --check

  build:
    name: Build SDK
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    strategy:
      matrix:
        target: ["nanos", "nanox", "nanosplus"]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p ledger_device_sdk --target ledger_device_sdk/${{ matrix.target }}.json

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    strategy:
      matrix:
        target: ["nanos", "nanox", "nanosplus"]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p ledger_device_sdk --target ledger_device_sdk/${{ matrix.target }}.json --features speculos
