name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_clippy_fmt:
    runs-on: ubuntu-latest
    steps:
      - name: arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1.0.3
        with:
          release: '9-2019-q4'
      - uses: actions/checkout@v2
      - run: python3 -m pip install pillow
      - name: Install thumbv6 target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: thumbv6m-none-eabi 
          components: rustfmt, clippy
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build 
          args: --features pre1_54
      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features pre1_54 -- -D warnings
      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
